# -*- coding: utf-8 -*-
"""ML-Lo_Rg

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kAm3d3bj2eghr0nyOpmDZqhl6Q-6r4O
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_auc_score, roc_curve, auc

data = load_breast_cancer()

df = pd.DataFrame(data.data, columns= data.feature_names)

df.head()

df.info()

df['target'] = data.target

data.target_names

df['target'].unique()

df.describe()

print(df.isnull().sum())

df.duplicated().sum()

x = df.drop('target', axis =1)
y = df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state = 42)

scale = StandardScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.fit_transform(x_test)

corr_mat = df.corr()
#corr_mat

plt.figure(figsize=(10,7))
sns.heatmap(corr_mat,annot= False,cmap='coolwarm')

sns.pairplot(df, vars=['mean radius', 'mean texture', 'mean perimeter', 'mean area'], hue='target')
plt.suptitle('Pairplot of Selected Features', y=1.02)
plt.show()

df.skew()

model = LogisticRegression()
model.fit(x_train,y_train)

y_pred = model.predict(x_test)

y_pred

acc = accuracy_score(y_test,y_pred)
print(acc)

mat = confusion_matrix(y_pred,y_test )
mat

y_pred_prob = model.predict_proba(x_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_pred_prob)
fpr, tpr, _ = roc_curve(y_test, y_pred_prob)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc='lower right')
plt.show()